name: lora-local
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip>=24.0
  - cudatoolkit=12.1  # optional; if using CUDA runtime from conda
  - pip:
      - torch
      - torchvision
      - transformers>=4.44.2
      - accelerate>=0.34.2
      - datasets>=2.21.0
      - bitsandbytes>=0.43.3
      - peft>=0.12.0
      - trl>=0.9.6
      - sentencepiece
      - protobuf
      - matplotlib
      - pyyaml
