seed: 42

model:
  base: Qwen/Qwen2.5-1.5B-Instruct
  lora:
    r: 8
    alpha: 16
    dropout: 0.1

train:
  # 8GB最小安全ライン
  seq: 256
  batch_size: 1
  grad_accum: 16
  lr: 1.0e-4
  scheduler: cosine
  warmup_ratio: 0.03
  epochs: 1
  packing: true
  logging_steps: 5
  save_steps: 200
  save_total_limit: 2

dataset:
  path: data/style_maid.jsonl
